publish_to: "none"

name: nocsis

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.5.4
  google_fonts: ^6.3.2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  json_annotation: ^4.8.1
  collection: ^1.18.0
  intl: ^0.20.2
  go_router: ^17.0.0
  animations: ^2.1.0
  dynamic_color: ^1.7.0
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  nil: ^1.1.1
  chopper: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  json_serializable: ^6.11.2
  go_router_builder: ^4.1.1
  chopper_generator: ^8.5.0
  swagger_dart_code_generator: ^4.1.0
  firebase_auth_mocks: ^0.15.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/weather/
    - assets/images/Icon-192.png
    - assets/images/google.svg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
